name: Deploy to staging
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    # uses GitHub environment
    environment:
      name: Staging
      url: "https://uat.employee.coloredcow.com"

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: whoami
